### PR TITLE
Fix derp

### PR DESCRIPTION
**Pull request by MasterKhatri**

### CODE REVIEW

**Comment by justks** [comment]
@MasterKhatri I don't call that a derp exactly. Lol xD

**Comment by MasterKhatri** [comment]
@kubersharma001 ,was it on purpose? 🤔

**Comment by mohancm** [comment]
@MasterKhatri Well, it had a merge commit
No more merge commits

**Comment by MasterKhatri** [comment]
@mohancm100,but I still can't see the change I.e.,it is still "Aplication"..maybe I'm missing something here? :0

**Comment by justks** [comment]
@MasterKhatri Do a proper commit or wait i will fix it - a small typo it is.

**Comment by MasterKhatri** [comment]
@kubersharma001 ,okay, you do it. :)

**Pull request closed without merging**
