### PR TITLE
Added Portuguese translation

### PR DESCRIPTION
**Pull request by ElTifo**

### CODE REVIEW

**Comment by mohancm** [comment]
@ElTifo have you tested?

**Comment by ElTifo** [comment]
Test it? How? Building the app?

Anyway, the translation is fine, trust me. Done it before on other apps/ROMs.

**Comment by mohancm** [comment]
Well, I will test it and merge
 if everything fine
Thanks @ElTifo

**Comment by ElTifo** [comment]
Ok. No problem.

**Pull request closed without merging**
